

# This file was *autogenerated* from the file hello.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2)# hello.sage
print("Hello, Sage!")
a = _sage_const_3 
b = _sage_const_4 
print("a^2 + b^2 =", a**_sage_const_2  + b**_sage_const_2 )


